### ISSUE TITLE
Research Yandex 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/AutopartsOrders#28]
Nyjno sdelat ne bolshoi takoi research pro yandex, s tochki zreniya regostracii nashei kompanii tam, mojem li mi? esli da to kyda imenno? est li y nix kakaya to karta tipa Google Maps ili eshe chto? 
Do Pyatnici nado postoratsya sdelat research.

**Comment by tilekazizbekov** [comment]
ok

**Comment by ghost** [comment]
yandex карта

**Comment by ghost** [comment]
Да, можно это сделать
Надо как обычно зарегиться там, потом уже регистрировать свою компанию как в Linkedin
https://yandex.ru/support/sprav/add-company/add-org.html
