### ISSUE TITLE
Vladimir AС: T. A. Verso 2005

### ISSUE THREAD

**Issue by ghost** [AndroidAkyl/AutopartsOrders#8]
1. колодки

**Comment by ghost** [comment]
1. товар найден
2. клиент оповещен
3. товар отправлен
4. клиент не доступен
5. з-з отменен

**Comment by ghost** [comment]
Клиент не доступен

**Comment by tilekazizbekov** [comment]
целесообразно снять заказ и вернуть продавцу
поскольку клиент так и не включился
